import { Schema } from "effect"
import { Coordinates } from "./Coordinates.ts"
import { StoryDraft } from "./StoryDraft.ts"

/** Public story with provider-backed coordinates and independently researched prose. */
export const ResearchStory = Schema.Struct({
  ...StoryDraft.fields,
  /** Coordinates matched to the supplied place ID, never generated by the model. */
  coordinates: Coordinates,
  /** Straight-line distance computed by the server. */
  distanceMeters: Schema.Number.pipe(Schema.between(0, 1000)),
  /** Compass direction computed by the server. */
  bearing: Schema.String,
})

/** Serializable ResearchStory contract inferred from its boundary schema. */
export type ResearchStory = typeof ResearchStory.Type
