import { Schema } from "effect"
import { Coordinates } from "./Coordinates.ts"
import { StoryDraft } from "./StoryDraft.ts"
import { boundedText } from "./boundedText.ts"

/** Public story with provider-backed coordinates and model-generated prose. */
export const ResearchStory = Schema.Struct({
  ...StoryDraft.omit("locationQuery").fields,
  /** Provider identifier obtained by geocoding the story's site. */
  placeId: boundedText(300),
  /** Coordinates resolved by the provider, never generated by the model. */
  coordinates: Coordinates,
  /** Straight-line distance computed by the server. */
  distanceMeters: Schema.Number.pipe(Schema.between(0, 1000)),
  /** Compass direction computed by the server. */
  bearing: Schema.String,
})

/** Serializable ResearchStory contract inferred from its boundary schema. */
export type ResearchStory = typeof ResearchStory.Type
