import { test, expect } from "@playwright/test"

test.use({ viewport: { width: 430, height: 932 } })

test("previews a new place, cancels safely, and commits only on Explore here", async ({ page }) => {
  // Exercise the independent text fallback without requiring Google credentials or network.
  await page.route("https://maps.googleapis.com/**", route => route.abort())
  await page.goto("/?research=fixture")
  const chooser = page.getByRole("combobox", { name: "Search for a place" })
  await expect(chooser).toHaveAttribute("placeholder", "candlemaker row")
  const fieldBounds = await chooser.boundingBox()
  const headerBounds = await page.getByText("tourist", { exact: true }).boundingBox()
  expect(Math.abs(fieldBounds!.y - headerBounds!.y)).toBeLessThan(5)
  await chooser.click()
  const mapChoice = page.getByRole("button", { name: "Choose on map" })
  await expect(mapChoice).toBeVisible()
  expect((await mapChoice.boundingBox())!.y).toBeGreaterThan(fieldBounds!.y)
  await mapChoice.click()
  const picker = page.getByRole("region", { name: "Choose a location" })
  await expect(picker).toBeVisible()
  await expect(page.getByRole("button", { name: /worst poet/ })).toBeVisible()
  const pickerBounds = await picker.boundingBox()
  const storiesBounds = await page.getByLabel("Stories and conversation").boundingBox()
  expect(storiesBounds!.y).toBeGreaterThanOrEqual(pickerBounds!.y + pickerBounds!.height)
  await page.getByRole("combobox", { name: "Search for a place" }).fill("Edinburgh Castle")
  await page.getByRole("button", { name: "Search", exact: true }).click()
  await expect(page.getByRole("button", { name: "Explore here" })).toBeEnabled()
  await expect(page.getByText("Edinburgh Castle", { exact: true })).toBeVisible()
  await page.getByRole("button", { name: "Cancel" }).click()
  await expect(chooser).toBeFocused()
  await expect(chooser).toHaveAttribute("placeholder", "candlemaker row")
  await expect(page.getByRole("button", { name: /worst poet/ })).toBeVisible()
  await chooser.click()
  await page.getByRole("combobox").fill("Edinburgh Castle")
  await page.getByRole("button", { name: "Search", exact: true }).click()
  await page.getByRole("button", { name: "Explore here" }).click()
  await expect(chooser).toHaveAttribute("placeholder", "edinburgh castle")
})
